### ISSUE TITLE
Move or fork to isapp/checkdotenv

### ISSUE THREAD

**Issue by paulodiovani** [wenderjean/settenv#6]
What do you think to move this repos to `isapp/checkdotenv`? So the whole _Is team_ can maintain it.

**Comment by wenderjean** [comment]
@paulodiovani  Can we keep it open? let's do it

**Comment by paulodiovani** [comment]
?

**Comment by wenderjean** [comment]
I mean, create an open repository on `isapp`, I'd suggest a fork, thereby we don't need to republish in NPM and just change the dependency in our services.

**Comment by paulodiovani** [comment]
Republish is not a problem. We just need to upgrade `repository` under `package.json` and increase minor version.

It doesn't make difference if it's a fork, a clone or if the repository is just moved.

**Comment by paulodiovani** [comment]
You can just ask _gabe_ or _chris_ to create the repos and push there. :package:

**Comment by wenderjean** [comment]
I'll do it.
