### ISSUE TITLE
Project should have a single source tree

### ISSUE THREAD

**Issue by paulodiovani** [wenderjean/settenv#8]
This is a reissue of #6, (re)opened due to some inconsistencies:

- [ ] This project and [isapp/checkdotenv](https://github.com/isapp/checkdotenv) are not forks of the same project.

- [ ] [wenderjean/checkdotenv](https://github.com/wenderjean/checkdotenv/issues/6) has more and most recent commits, but [isapp/checkdotenv](https://github.com/isapp/checkdotenv) has a lot more releases

- [ ] [NPM Package](https://www.npmjs.com/package/checkdotenv) points to [wenderjean/checkdotenv](https://github.com/wenderjean/checkdotenv/issues/6), but versions/releases don't match

Since they were created for the same reason (and from the same codebase) I think it's better to keep a single source tree. Forks are not a problem, but two unrelated projects with the same name are.

We must decide which project is the _correct_ one and get rid of the other to encourage collaboration.

CC: @elomar

**Comment by wenderjean** [comment]
@paulodiovani I don't think `isapp` will maintain the project, so I vote to apply the changes you sent in #9 and release them in `npm`.

What do you think?

**Comment by paulodiovani** [comment]
That's ok for me.

**Comment by paulodiovani** [comment]
Fixed in #9
